### ISSUE TITLE
Invalid MIDI data.

### ISSUE THREAD

**Issue by TwistXL** [thewildwestmidis/thewildwestmidis.github.io#1]
Hello, MIDI: https://thewildwestmidis.github.io/midis/Whistle%20-%20Flo%20Rida%20[MIDICollection.net].mid
doesn't work. I just get the old Invalid MIDI data when I insert it into game. Please fix this when you can. Thank you

-- TwistXL

**Comment by Bertogim** [comment]
I looked into it and it looks like all the midis that have square brackets `[ ]` dosnt work, i will rename them and change the square brackets to normal brackets `( )` wich seem to work
List of midis affected: [https://thewildwestmidis.github.io/?search=%5B](https://thewildwestmidis.github.io/?search=%5B)
Thanks for letting me know!

**Comment by Bertogim** [comment]
Done! I renamed all the midis that had square brackets to normal brackets

EDIT: This is even more fixed for other characters and this one since the April 1 update, improving link coping

**Comment by TwistXL** [comment]
Thank you!
