### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by TwistXL** [thewildwestmidis/thewildwestmidis.github.io#2]
Hello, me again. I just wanted to say thank you for making this wonderful website for people who can't exactly find good websites for MIDIs to use on Roblox. I just wanted to add that you should add a bit of colour to the website. (metaphorically) It just looks bland with the grey. If it disrupts anything with the MIDIs I do not mind. Thank you.

--TwistXL

**Comment by Bertogim** [comment]
Its true, but i never came with a good idea to color the website, i maybe one idea i have is making background images (Of The Wild West)

**Comment by Bertogim** [comment]
I added backgound images as a test, to see it, add ?test1 in the url and if people likes it, i will add it
btw, there is a image per month, so there is variation

[https://thewildwestmidis.github.io/?test1](https://thewildwestmidis.github.io/?test1)

It definetly needs a upgrade changing more things, not only the background

**Comment by TwistXL** [comment]
> I added backgound images as a test, to see it, add ?test1 in the url and if people likes it, i will add it btw, there is a image per month, so there is variation
> 
> https://thewildwestmidis.github.io/?test1
> 
> It definetly needs a upgrade changing more things, not only the background

The test you sent through is wonderful! You should add it sometime soon.!

**Comment by Bertogim** [comment]
I upgraded it:

### Test1 (Old)

[https://thewildwestmidis.github.io/?test1a](https://thewildwestmidis.github.io/?test1a) - Background test
Add `?test1a` at any page

[https://thewildwestmidis.github.io/?test1b](https://thewildwestmidis.github.io/?test1b) - The same but with random Background
Add `?test1b` at any page

### Test2 (New)
The test2 changes transparency to certain elements

[https://thewildwestmidis.github.io/?test2a](https://thewildwestmidis.github.io/?test2a) - Background test with extra fixed things and transparency
Add `?test2a` at any page

[https://thewildwestmidis.github.io/?test2b](https://thewildwestmidis.github.io/?test2b) - The same but with random Background
Add `?test2b` at any page

Let me know if you like it!

**Comment by Bertogim** [comment]
I published the Test2! (A lot of people were asking me to add the design update (Test2) )
Let me know if you like it! And we can close this

**Comment by TwistXL** [comment]
> I published the Test2! (A lot of people were asking me to add the design update (Test2) ) Let me know if you like it! And we can close this

I'm loving the new background! Thank you for putting time into this!

Gracias!
